#!/usr/bin/env node
// tools/gen-sitemap.js — rebuild sitemap.xml from data.js + static pages.
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");
const SITE = "https://h4efyx8v.autoclawai.space"; // regenerate with final domain when published
const src = fs.readFileSync(path.join(ROOT, "assets", "js", "data.js"), "utf8");
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(src, ctx);
const P = ctx.window.POZIVERSE;
if (!P) { console.error("FATAL: could not evaluate data.js"); process.exit(1); }

const today = new Date().toISOString().slice(0, 10);
const staticPages = [
  ["/", "1.0"], ["/watch.html", "0.8"], ["/replies.html", "0.8"], ["/annex.html", "0.9"],
  ["/club.html", "0.8"], ["/downloads.html", "0.7"], ["/library.html", "0.7"],
  ["/now.html", "0.6"], ["/about.html", "0.5"], ["/signin.html", "0.3"],
];
const articlePages = [...P.ARTICLES]
  .sort((a, b) => (b.date || "").localeCompare(a.date || ""))
  .map(a => [`/article.html?id=${a.slug}`, "0.9", a.date]);

const urls = [
  ...staticPages.map(([p, pr]) => `  <url><loc>${SITE}${p}</loc><lastmod>${today}</lastmod><priority>${pr}</priority></url>`),
  ...articlePages.map(([p, pr, d]) => `  <url><loc>${SITE}${p}</loc><lastmod>${d || today}</lastmod><priority>${pr}</priority></url>`),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/gen-sitemap.js ${today}. Regenerate with the final domain when published. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>
`;
const out = path.join(ROOT, "sitemap.xml");
fs.writeFileSync(out + ".tmp", xml, "utf8");
fs.renameSync(out + ".tmp", out);
console.log(`sitemap.xml rebuilt: ${urls.length} URLs`);
